name: Compile Thesis

on:
  push:
    paths:
      - 'paper/**'
      - '.github/workflows/compile-thesis.yml'

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Typst
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          cargo install --locked typst-cli
      
      - name: Compile Thesis
        run: typst compile paper/main.typ paper/main.pdf
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: paper/main.pdf
          tag_name: thesis-${{ github.sha }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
